### ISSUE TITLE
数据代码解耦

### ISSUE THREAD

**Issue by liangzid** [3vau/cndict#1]
非常不错的项目！

在阅读代码时的个人观点： 看文中的数据格式像是Dict和Array的组合，改成json格式存储每次需要时加载到内存里是否是一种更好的设计呢？如此一来，可以提供几种不同型号的配置，用一套代码去加载它～

**Comment by calsys456** [comment]
谢谢你的建议！很抱歉这两天有些忙，隔了好久才看见QAQ

cndict的数据格式是emacs-lisp中的哈希表，每次require cndict的时候加载到内存中，使用emacs进行读取相当方便，我认为比起直接使用json要节约一点性能，直接require .el文件的速度也比json-parse-string要快一些。不过我并没有仔细研究过emacs解析json和解析哈希表的代码，所以具体孰优孰劣我也不是很清楚，还请前辈提点！

我在实际使用中也发现，cndict的使用频率不是很高，require时加载词典数据确实可能拖慢启动速度，得不偿失。我稍后修改一下代码，让cndict在第一次使用时加载词典。

有任何问题欢迎告诉我！我一定多上github quq

**Comment by calsys456** [comment]
哦对了，如果你需要我处理过后的词典文件的话，我可以单独做成json发给你ww

**Comment by liangzid** [comment]
原来是性能原因啊……我前两天试图自己改一版cndict出来自己用，因为我觉得这个工具对我十分不错，但是因为一些事情一直都没改：(
我注意到这个数据是来自readme里的一个链接，还过去看了看。请问你的词典和那个repo里的有什么不同吗？如果没有什么不同我就直接去用那里的。感谢lz。

**Comment by calsys456** [comment]
嘿嘿，谢谢你能喜欢它！;)

cndict主要是重新组织了一下chinese-dictionary的数据结构，它原本的结构……可以说非常严谨吧，json嵌套层数非常多，cndict这种小项目完全用不到，我把它简化了一下，给我的小脑瓜减减负；同时还舍弃了部分内容，像quote、usage什么的。其它的基本没有区别。

还有任何建议都可以提出来:D

很推荐你去支持一下chinese-dictionary，别看star数不多，作者可是很用心地把网上绝大部分的资料全都整合了一遍，十分齐全。
